### ISSUE TITLE
Discussion: Use of PyXB in TEASER

### ISSUE THREAD

**Issue by PRemmen** [RWTH-EBC/TEASER#508]
## What is the problem?

1. Developer of pyxb wants to stop support for pyxb / searches for new maintainer
2. Namespaces in pyxb bindings currently causes errors when executing in IPython console (probably problem with our xsd schema)

## Why do we want to solve it?

- To have a robust way to manage our internal databases

## How do we want to solve it?

- find good replacement for pyxb and/or correct bindings/xsd schemas

**Comment by BrendanSulliv** [comment]
Hi I'm trying to use TEASER to make low order building models for Modelica.
I'm trying to run e1_generate_archetype.py but it gives me the following error:

NamespaceUniquenessError: http://teaser.boundary: name integerList used for multiple values in typeBinding

Which comes from pyxb being used in the boundaryconditions_bind.py file. Is this issue related to this?

**Comment by PRemmen** [comment]
@BrendanSulliv yes, kind off, but I thought this would have been fixed some versions ago. 

Two questions:

1. Are you running the latest version of teaser? 
2. do you by chance run the script in an ipython console (like spyder)? we have had some problems with pyxb and spyder.

**Comment by BrendanSulliv** [comment]
@PRemmen 
Yes I was using Spyder, I've changed to IDLE and I still can't get the code running.
I reinstalled TEASER using pip install -U teaser
teaser is version 0.6.0
pyxb is version 1.2.5

Here are the problems I encounter with running e1_generate_archetype.py
1.     import teaser.data.bindings.v_0_6.boundaryconditions_bind as uc_bind
ModuleNotFoundError: No module named 'teaser.data.bindings.v_0_6'

Correction: I duplicated the files from teaser.data.bindings.v_0_4 into a new folder named teaser.data.bindings.v_0_6

2. raise pyxb.NamespaceUniquenessError(self, '%s: name %s used for multiple values in %s' % (self, local_name, category))
pyxb.exceptions_.NamespaceUniquenessError: http://teaser.boundary: name integerList used for multiple values in typeBinding

Correction: line 31 in project_bind.py calls for an import from v_0_4. Changing this line to read import "teaser.data.bindings.v_0_**6**.boundaryconditions_bind as \" corrects this.

3.     from teaser.logic.archetypebuildings.tabula.de.singlefamilyhouse import \
ModuleNotFoundError: No module named 'teaser.logic.archetypebuildings.tabula'

Correction: There is no folder under archetypebuildings named tabula, I simply commented out all of the tabula related import statements.

4.     raise pyxb.NamespaceError(self, '%s has no category %s' % (self, category))
pyxb.exceptions_.NamespaceError: http://teaser/0.6/elements has no category elementBinding

Correction: Not sure what to do about this error. It seems to stem from the typeelement_bind.py file which may have something to do with problem 1.

Please advise

**Comment by PRemmen** [comment]
ahh I just saw that version 0.6.1. is not available on pip yet, we'll fix that very soon

**Comment by BrendanSulliv** [comment]
@PRemmen 
Ok after updating to 0.6.1 the examples all run without error.

However, I am now trying to simulate the buildings generated in e3 using OpenModelica v1.13.0 and I get numerous warnings and errors. The ones I think are important are:

[1] 10:50:44 Translation Warning
Ignoring unknown experiment annotation option: __Dymola_Algorithm = "Cvode"

[2] 10:50:44 Symbolic Warning
[Modelica.Blocks.Sources: 2346:7-2347:66]: Unused input variable tableAvailable in function .Modelica.Blocks.Sources.CombiTimeTable$internalGains.getDerTableValue.

and

[1] 10:58:24 Symbolic Error
Too many equations, over-determined system. The model has 1501 equation(s) and 1357 variable(s).

Any thoughts?

**Comment by BrendanSulliv** [comment]
To simulate in OpenModelica I opened the package.mo file found under TEASEROutput>ArchetypeExample and opened the ResidentialBuildingTabula_SingleDwelling with default simulation settings

**Comment by PRemmen** [comment]
Sorry, I have not tested OpenModelica for a long time.

Did you try `e3_export_ibpsa_models.py`? These models are little bit more "basic" as aixlib models, so they might actually work in OpenModelica. but can't give you any guarantee

**Comment by nwkd** [comment]
Hi, I am trying to build up a district energy simulation based on CityGML input data. The teaser and PyXB versions are

	PyXB==1.2.5
	teaser==0.6.4

When trying to execute

	from teaser.project import Project
	prj = Project(load_data=True)
	prj.load_citygml("house.gml")

I get the error message

	Traceback (most recent call last):
	  File "/home/dano/.local/lib/python3.6/site-packages/pyxb/namespace/__init__.py", line 307, in categoryMap
	    return self.__categoryMap[category]
	KeyError: 'elementBinding'
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "teaser-test.py", line 3, in <module>
	    prj.load_citygml("house.gml")
	  File "/home/dano/.local/lib/python3.6/site-packages/teaser/project.py", line 1276, in load_citygml
	    citygml_in.load_gml(path, self)
	  File "/home/dano/.local/lib/python3.6/site-packages/teaser/data/input/citygml_input.py", line 47, in load_gml
	    gml_bind = citygml.CreateFromDocument(xml_file.read())
	  File "/home/dano/.local/lib/python3.6/site-packages/teaser/data/bindings/opengis/citygml/raw/base.py", line 74, in CreateFromDocument
	    saxer.parse(io.BytesIO(xmld))
	  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
	    xmlreader.IncrementalParser.parse(self, source)
	  File "/usr/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
	    self.feed(buffer)
	  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
	    self._parser.Parse(data, isFinal)
	  File "../Modules/pyexpat.c", line 414, in StartElement
	  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 370, in start_element_ns
	    AttributesNSImpl(newattrs, qnames))
	  File "/home/dano/.local/lib/python3.6/site-packages/pyxb/binding/saxer.py", line 324, in startElementNS
	    element_binding = name_en.elementBinding()
	  File "/home/dano/.local/lib/python3.6/site-packages/pyxb/namespace/__init__.py", line 104, in __getattr__
	    category_value = ns.categoryMap(name).get(self.localName())
	  File "/home/dano/.local/lib/python3.6/site-packages/pyxb/namespace/__init__.py", line 309, in categoryMap
	    raise pyxb.NamespaceError(self, '%s has no category %s' % (self, category))
	pyxb.exceptions_.NamespaceError: http://www.opengis.net/citygml/1.0 has no category elementBinding

This happens using Python 2.7.15rc1 as well as Python 3.6.6. Am I doing something essentially wrong, or is there anything I can do?

**Comment by MichaMans** [comment]
Hi @nwkd ,

thanks for trying out TEASER. From a first look and with the help of @PRemmen it could be that you are using a citygml version not supported. Currently we only have the citygml 2.0 bindings implemented. Is it possible to give the citygml 2.0 version a try?

**Comment by nwkd** [comment]
Hi @MichaMans, I tried out the TEASER CityGML example file which seems to work well on my machine. So I'll try to convert my gml input files or use another data source. Thanks a lot!

**Comment by PRemmen** [comment]
@nwkd for very most CityGML files you can just change the namespace "hardcode" from 1.0 to 2.0 because there are no major changes in the schema :) Good Luck!

**Comment by PRemmen** [comment]
Back to topic: I'll probably will change whole data package to get rid of pyxb at all and switch to json. This will imply that we will lose all backwards compatibility.

**Comment by PRemmen** [comment]
My proposal is:

1. make a release 0.7.0 where we keep the possibility to load old XML and still have pyxb as an input (I'm preparing that in branch "issue510_usecond"
2. delete all pyxb files and xml dependencies
3. make a new release 0.8.0 that is exactly the same as 0.7.0 but without any dependency of pyxb

**Comment by MichaMans** [comment]
Maybe we can think about a major release as we are loosing backwards compatibility.
